name: photopulse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  # github_sign_in_plus: ^0.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  extended_image: ^8.2.0
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.1
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  flutter_staggered_animations: ^1.1.1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  gallery_saver: ^2.3.2
  gap: ^3.0.1
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.3
  http_client_helper: ^3.0.0
  image: ^4.1.7
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  material_floating_search_bar_2: ^0.5.0
  oauth2: ^2.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  q_architecture: ^0.1.8
  readmore: ^2.2.0
  remove_emoji_input_formatter: ^0.0.1+1
  responsive_framework: ^1.1.1
  retrofit: ^4.0.2
  sentry_flutter: ^7.10.1
  shake: ^2.2.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.4.4

dev_dependencies:
  build_runner: ^2.4.6
  # dart_code_metrics: ^5.7.6
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  retrofit_generator: null
  state_notifier_test: ^0.0.10

flutter_native_splash:
  image: assets/images/launcher.png
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"

flutter_icons:
  ios: true
  # android: true
  android: "launcher_icon"
  image_path_ios: "assets/images/launcher.png"
  image_path_android: "assets/images/launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cocogoose Pro
      fonts:
        - asset: assets/fonts/Cocogoose Pro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cocogoose Pro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cocogoose Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cocogoose Pro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cocogoose Pro-Light.ttf
          weight: 300
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Thin.ttf
          weight: 300
