name: photopulse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  either_dart: ^1.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  go_router: ^11.1.3
  hooks_riverpod: ^2.4.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  q_architecture: ^0.1.5
  remove_emoji_input_formatter: ^0.0.1+1
  responsive_framework: ^1.1.1
  retrofit: ^4.0.2
  reusable_widgets_docs_generator:
    git:
      url: https://oauth2:glpat-ZzPwb9jEhQzH8ZRubL8E@gitlab.qagency.io/flutter/reusable-widget-generator.git
      ref: master
  sentry_flutter: ^7.10.1
  shake: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.6
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  retrofit_generator: null
  state_notifier_test: ^0.0.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cocogoose Pro
      fonts:
        - asset: assets/fonts/Cocogoose Pro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cocogoose Pro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cocogoose Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cocogoose Pro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cocogoose Pro-Light.ttf
          weight: 300
    - family: FreightSans Pro
      fonts:
        - asset: assets/fonts/FreightSans Pro-Bold.ttf
          weight: 700
        - asset: assets/fonts/FreightSans Pro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FreightSans Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/FreightSans Pro-Regular.ttf
          weight: 400
        - asset: assets/fonts/FreightSans Pro-Light.ttf
          weight: 300
